import '../styles/globals.css';
import Head from 'next/head';
import Page from '../layout/Page';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Kera</title>
        <meta charset='UTF-8' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
        />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />
      </Head>
      <Page>
        <Component {...pageProps} />
      </Page>
    </>
  );
}

export default MyApp;
